"""Add campus_id to Users table

Revision ID: f5ddc49acff3
Revises: a02c5bf43407
Create Date: 2024-06-03 00:34:51.796814

"""
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ddc49acff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('campus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'campuses', ['campus_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'campus_id')
    # ### end Alembic commands ###
